Rt 662 grid colin: In the cardio-patient app, the chart should be optimized for mobile devices and should be easy to read on a small screen.
elimuinformatics/charts-on-fhir pull request #125
Opened 2023-03-10 13:57 UTC by amolht

## Overview

-Added a CSS grid layout for app mobile responsive

## How it was tested

-Tested it by launching the cardio-patient app locally in different mobile views.
Also tested showcase-web and cardio-health locally.

## Checklist

- [X] The title contains a short meaningful summary
- [X] I have added a link to this PR in the Jira issue
- [X] I have described how this was tested
- [X] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [X] I have run unit tests locally
- [ ] I have updated documentation (including README)
![image](https://user-images.githubusercontent.com/57406228/224334160-12b57519-5e67-4905-839b-559cd10b5374.png)

![image](https:/
![image](https://user-images.githubusercontent.com/57406228/224334344-d4812de6-a66c-419e-97e3-f3af65cd7ed8.png)
/user-images.githubusercontent.com/57406228/224334245-dd63cdb0-09d3-4981-882e-9d3ddda19fbf.png)
![image](https://user-images.githubusercontent.com/57406228/224334461-11feb4c3-fc3f-43c9-95bd-7578ad8f053a.png)

2023-03-10 14:23 UTC, semicolin requested changes
This PR is reverting some changes from a PR that I merged yesterday. I think you resolved the merge conflict in the wrong direction.

2023-03-13 16:06 UTC, semicolin submitted a review, later dismissed

2023-03-14 05:59 UTC, yashpmohod submitted a review, later dismissed

2023-03-14 06:27 UTC, yashpmohod approved these changes

2023-03-14 06:30 UTC, merged