RT-684-ExpressionChangedAfterItHasBeenCheckedError
elimuinformatics/charts-on-fhir pull request #138
Opened 2023-03-16 13:10 UTC by yashpmohod

## Overview
use `ChangeDetectorRef` to manipulate the tree.
![image](https://user-images.githubusercontent.com/117890382/225627042-457be690-1928-41c0-b33d-7c3747c79f5c.png)

## How it was tested
Tested using run showcase app locally using mock-fhir server and ngx-charts-on-fhir server.

## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-03-17 13:36 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.spec.ts
> +  timelineRange$ = of({ min, max }).pipe(delay(0));
why did you add a delay to the mock config service?

2023-03-17 16:02 UTC, semicolin requested changes

2023-03-17 16:02 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.spec.ts
> +import { delay, of } from 'rxjs';
unused import

2023-03-20 06:06 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.spec.ts
> +import { delay, of } from 'rxjs';
Okay, @semicolin I will remove unused imports.

2023-03-20 06:07 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.spec.ts
> +  timelineRange$ = of({ min, max })
Okay @semicolin

2023-03-20 13:40 UTC, semicolin approved these changes

2023-03-20 14:15 UTC, merged