RT-745-Shorten-Systolic/Diastolic-labels
elimuinformatics/charts-on-fhir pull request #179
Opened 2023-04-24 08:30 UTC by yashpmohod

## Overview
In `blood-pressure-mapper.service.ts` change the labels of `annotationOptions`.
Write the `removeBloodPressureLabel` common function in `utils.ts`, For checking and removing `Blood pressure` from the dataset and annotation label.

## How it was tested
Tested using run all `charts-on-fhir` apps locally.

## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-04-24 08:34 UTC, yashpmohod commented
After removing `Blood Pressure` from the dataset label and annotation label content.
![image](https://user-images.githubusercontent.com/117890382/233942263-d829ad6a-a503-4137-830c-34e213a3cc86.png)
![image](https://user-images.githubusercontent.com/117890382/233942850-a4813e2f-959c-4299-94f4-0444f3b4c434.png)
![image](https://user-images.githubusercontent.com/117890382/233943010-a74e33b3-8612-4c25-9fdc-ded7b04d192b.png)

2023-04-24 13:55 UTC, semicolin requested changes
We should not add a special case for BP in the list components. We should just change the label for those datasets when mapping them.

2023-04-25 13:41 UTC, semicolin requested changes

2023-05-01 18:23 UTC, semicolin commented
@yashpmohod This PR is no longer needed. I have another solution for customizing layer names and matching annotations.

2023-05-03 09:24 UTC, closed without merging