RT743 customize summary timeframe colin
elimuinformatics/charts-on-fhir pull request #192
Opened 2023-05-03 14:54 UTC by amolht

## Overview
Added Customize Summary Timeframe
Created separate component to select timeframe summary for 1mo, 3mo, 6mo, 1year
Updated a CSS so all the selectors should align 
in Showcase timeframe component overflow I will work on CSS and fix that, cardiovascular heth app it show properly align  
Added timeframe for the cardio-health and showcase

## How it was tested

Tested all charts-on-fhir apps on locally.
Ran unit test locally.

## Checklist

- [X] The title contains a short meaningful summary
- [X] I have added a link to this PR in the Jira issue
- [X] I have described how this was tested
- [X] I have included screen shots for changes that affect the user interface
- [X] I have updated unit tests
- [X] I have run unit tests locally
- [x] I have updated documentation (including README)
![image](https://user-images.githubusercontent.com/57406228/235954094-ce02023c-a1bd-42c9-9dc0-46899428d93b.png)

2023-05-03 17:15 UTC, semicolin requested changes

2023-05-03 17:15 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/data-layer-selector/data-layer-selector.component.css
> +}
why is this here? data-layer-selector component does not have a mat-button-toggle-group.

2023-05-03 19:15 UTC, semicolin approved these changes

2023-05-04 05:37 UTC, yashpmohod approved these changes

2023-05-04 10:42 UTC, merged