Updated the data layer merge service to create hashcode using layer name
elimuinformatics/charts-on-fhir pull request #248
Opened 2024-05-31 09:47 UTC by shubhamparikh927

## Overview
- Updated the data layer merge service to generate hashcode id using layer name

## How it was tested
- Tested by running showcase app locally
- Verified that no duplicate datalayer is created if there a minor difference in metadata 

## Checklist

- [x] The title contains a short meaningful summary
- [x] I have added a link to this PR in the Jira issue
- [x] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [x] I have run unit tests locally
- [ ] I have updated documentation (including README)

2024-05-31 14:27 UTC, semicolin commented
This is a potentially high-impact change. I'm going to do some testing on this branch.

2024-05-31 17:50 UTC, semicolin commented
I don't think we should merge this PR. It could result in inaccurate information being displayed in the chart. For example, the demo patient "Ocelot Apricot" has multiple hemoglobin observations. Some are measured in `mmol/L` and others are measured in `g/dL`. In this branch, they both show up on the same scale, which is labelled `g/dL`. The measurement of `15 mmol/L` is misrepresented as `15 g/dL`. Those are not equivalent. We would need to do unit conversion in order to display those on the same chart. 

Instead, we should change the observation mappers to use `resource.valueQuantity.code` instead of `resource.valueQuantity.unit` for the scale label. That will eliminate duplicate layers that are caused by cosmetic differences in the human-readable display units without merging layers that really use different units of measure.

We should also continue troubleshooting the bugs that we see when there are two layers with the same name. We should be able to support multiple layers with the same name. Maybe it is actually an issue with the dataset labels being the same? Dataset labels do need to be unique due to chart.js requirement.

2024-06-03 13:48 UTC, semicolin requested changes

2024-06-03 13:48 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
> +        title: { text: [layerName, resource.component[0].valueQuantity.code] },
need to do the same for SimpleObservationMapper

2024-06-03 13:48 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
> +            valueQuantity: { value: 7, unit: 'unit', code: 'unit' },
we should use different values for `unit` and `code` so the test will fail if the mapper is using the wrong property.

2024-06-03 16:36 UTC, semicolin approved these changes

2024-06-04 05:47 UTC, vdeshkar approved these changes

2024-06-04 08:22 UTC, merged