documentation publish failing
elimuinformatics/charts-on-fhir pull request #255
Opened 2024-06-24 07:19 UTC by shubhamparikh927

## Overview
- Updated the release.yml to remove the unwanted CP command for angular routing

## How it was tested
- Not Tested

## Checklist

- [x] The title contains a short meaningful summary
- [x] I have added a link to this PR in the Jira issue
- [x] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2024-06-24 16:55 UTC, semicolin requested changes
I don't think this is the right solution. If you run a build locally and look at the `dist` dir, the application is now under a `/browser` subdir. We will need to append `/browser` to the paths in build-docs job.

I think the `cp` command is still needed. The Angular 17 documentation for [deploying to GitHub pages](https://v17.angular.io/guide/deployment#deploy-to-github-pages) still has this step:
> 5. When the build is complete, make a copy of docs/index.html and name it docs/404.html.

2024-06-25 06:12 UTC, shubhamparikh927 commented
> I don't think this is the right solution. If you run a build locally and look at the `dist` dir, the application is now under a `/browser` subdir. We will need to append `/browser` to the paths in build-docs job.
> 
> I think the `cp` command is still needed. The Angular 17 documentation for [deploying to GitHub pages](https://v17.angular.io/guide/deployment#deploy-to-github-pages) still has this step:
> 
> > 5. When the build is complete, make a copy of docs/index.html and name it docs/404.html.

2024-06-25 06:14 UTC, shubhamparikh927 commented
> I don't think this is the right solution. If you run a build locally and look at the `dist` dir, the application is now under a `/browser` subdir. We will need to append `/browser` to the paths in build-docs job.
> 
> I think the `cp` command is still needed. The Angular 17 documentation for [deploying to GitHub pages](https://v17.angular.io/guide/deployment#deploy-to-github-pages) still has this step:
> 
> > 5. When the build is complete, make a copy of docs/index.html and name it docs/404.html.

I have tested it as you suggested, It's working. So how should I have to publish the docuem

2024-06-25 06:20 UTC, shubhamparikh927 commented
> I don't think this is the right solution. If you run a build locally and look at the `dist` dir, the application is now under a `/browser` subdir. We will need to append `/browser` to the paths in build-docs job.
> 
> I think the `cp` command is still needed. The Angular 17 documentation for [deploying to GitHub pages](https://v17.angular.io/guide/deployment#deploy-to-github-pages) still has this step:
> 
> > 5. When the build is complete, make a copy of docs/index.html and name it docs/404.html.

I have tested it as you suggested, It's working, But now how should I have to publish the documentation as it runs on the new release. Should I have to release a new version for that?

2024-06-25 16:50 UTC, semicolin requested changes

2024-06-25 16:50 UTC, semicolin commented on .github/workflows/release.yml
> +      - run: cp dist/apps/documentation/browser/index.html dist/apps/documentation/404.html # Needed for Angular routing
Documentation site is not working: https://elimuinformatics.github.io/charts-on-fhir/
You also need to add /browser to the cp destination path and the upload-pages-artifact path

2024-06-25 16:54 UTC, semicolin commented
> > I don't think this is the right solution. If you run a build locally and look at the `dist` dir, the application is now under a `/browser` subdir. We will need to append `/browser` to the paths in build-docs job.
> > I think the `cp` command is still needed. The Angular 17 documentation for [deploying to GitHub pages](https://v17.angular.io/guide/deployment#deploy-to-github-pages) still has this step:
> > > 5. When the build is complete, make a copy of docs/index.html and name it docs/404.html.
> 
> I have tested it as you suggested, It's working, But now how should I have to publish the documentation as it runs on the new release. Should I have to release a new version for that?

No need to release a new version. Just deploy it from this branch like you did before and verify that the documentation site is working.

2024-06-26 06:19 UTC, vdeshkar approved these changes

2024-06-26 15:44 UTC, semicolin approved these changes

2024-06-27 05:29 UTC, merged