Updated a ngx-charts-on-fhir lib to used standalon component
elimuinformatics/charts-on-fhir pull request #259
Opened 2024-10-03 11:57 UTC by yashpmohod

## Overview

updated ngx-charts-on-fhir lib to use a standalone component.
in the first commit, I have just updated all the services and components. 
 

## How it was tested

## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2024-10-07 01:22 UTC, semicolin requested changes

2024-10-07 01:22 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/fhir-chart-layout/fhir-chart-layout.component.ts
> +    },
`PatientService` is provided in both `FhirChartLayoutComponent` and showcase `AppComponent`, so they are using different instances of the service and the app will not update when you select a patient in the patient browser.

2024-10-07 01:22 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
> +        { provide: ReferenceRangeService, useClass: ReferenceRangeService },
Prefer the shorthand provider syntax `ClassName` over the more verbose `{ provide: ClassName, useClass: ClassName }`

2024-10-07 01:22 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-options/annotation-options.component.ts
> +import { FormBuilder, NG_VALUE_ACCESSOR, ReactiveFormsModule } from '@angular/forms';
unused imports?

2024-10-07 10:43 UTC, yashpmohod commented on libs/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.spec.ts
> +    colorService = new DataLayerColorService(palette);
yes @semicolin we mocking this in other components' tests aswell.

2024-10-07 12:48 UTC, yashpmohod commented on libs/ngx-charts-on-fhir/src/lib/provide-charts-on-fhir.ts
> +    },
@semicolin I was getting a nullInjector error but I think it is because of another reason.

2024-10-08 13:17 UTC, semicolin commented on libs/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.spec.ts
> +    colorService = new DataLayerColorService(palette);
it looks like we are creating a real `DataLayerColorService`

2024-10-08 13:17 UTC, semicolin approved these changes

2024-10-08 13:20 UTC, shubhamparikh927 approved these changes

2024-10-09 06:49 UTC, shubhamparikh927 approved these changes

2024-10-09 06:50 UTC, merged