RT-554:Summary card title is too long
elimuinformatics/charts-on-fhir pull request #40
Opened 2023-01-13 14:38 UTC by yashpmohod

## Overview

Add ellipses on the Dataset Label, and layer name.
Also, Add a hover tooltip on the dataset label, layer name, and summary card title.

## How it was tested

Tested using run showcase app locally.

## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-01-13 19:14 UTC, semicolin requested changes
I suggest tweaking the `max-width`s a bit so the sidenav keeps the same size when switching panels, and to fill a bit more empty space on the summary card. See suggestions below.

2023-01-16 07:46 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/analysis-cards/analysis-card/analysis-card.component.css
> +  max-width: 250px;
Okay, I will change max-width:250px to max-width:350px

2023-01-16 07:46 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.css
> +  max-width: 370px;
Okay, I will change max-width:370px to max-width:300px

2023-01-16 07:47 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.css
> +  max-width: 471px;
Okay, I will change max-width:471px to max-width:450px

2023-01-16 07:47 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.html
> +          <mat-title matTooltip={{dataset.label}}>
Okay, I will change that.

2023-01-16 14:39 UTC, semicolin approved these changes

2023-01-17 06:41 UTC, merged