RT-577:6mo button stays selected after zooming
elimuinformatics/charts-on-fhir pull request #43
Opened 2023-01-16 13:08 UTC by yashpmohod

## Overview

1

## How it was tested

1
## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-01-16 14:37 UTC, semicolin requested changes
I recommend deleting this branch and starting over. It shouldn't be this complicated.
The range-selector component already knows the minDate and maxDate. All you need is a function that converts minDate/maxDate into a "onemonth" | "threemonth" | etc. so you can bind it to the mat-button-toggle-group's `[value]`

2023-01-16 14:37 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
> +    const that=this;
this is an anti-pattern. use an arrow function instead.

2023-01-16 14:37 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
> +        }
why do we need to listen to this event? range-selector is already getting the min/max from `layerManager.timelineRange$` every time the scale bounds change.

2023-01-16 14:37 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
> +        }
Also, why is it toggling the state on each zoom? is that really the right behavior?

2023-01-16 14:37 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.ts
> +  }
why do we need a setter for this instead of a simple property? the setter is not doing anything except setting the value.

2023-01-16 14:37 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.ts
> +  }
it looks like this is doing the exact same thing as the setter? why do we need so much complexity and duplication just to set a property value?

2023-01-17 19:08 UTC, semicolin requested changes

2023-01-19 11:04 UTC, yashpmohod commented
we have created another PR for the RT-577 branch.

2023-01-19 11:04 UTC, closed without merging