Docker
elimuinformatics/charts-on-fhir pull request #50
Opened 2023-01-19 03:40 UTC by semicolin

## Overview

- Created Dockerfile and NGINX config
- It should work for any app that we add to the workspace

## How it was tested

- Built Docker image and ran the container locally
- Tested SMART-on-FHIR launch from Logica Sandbox

## Checklist

- [x] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-01-19 04:47 UTC, amolht submitted a review, later dismissed

2023-01-19 14:33 UTC, hankwallace requested changes
Some minor changes requested.

2023-01-19 14:33 UTC, hankwallace commented on Dockerfile
> +ENTRYPOINT ["nginx", "-g", "daemon off;"]
I don't think overriding the entrypoint is needed. See the api-sidecar repos where we use nginx.
```
CMD ["nginx"]
```

2023-01-19 14:33 UTC, hankwallace commented on nginx.conf
> +
Add:
```
# Process needs to run in foreground within container
daemon off;
```

2023-01-20 00:22 UTC, hankwallace approved these changes

2023-01-20 14:17 UTC, merged