RT-577 :6mo button stays selected after zooming
elimuinformatics/charts-on-fhir pull request #52
Opened 2023-01-19 10:49 UTC by yashpmohod

## Overview
We use the onZoomStart on that, we ate removing the focus of the range selector.
Changes in test cases because we rename the component function name and MatButtons Id.

## How it was tested
Tested using run showcase app locally.

## Checklist

- [ ] The title contains a short meaningful summary
- [ ] I have added a link to this PR in the Jira issue
- [ ] I have described how this was tested
- [ ] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [ ] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-01-19 11:03 UTC, yashpmohod commented
we have created another PR for the RT-577 branch.

2023-01-19 14:05 UTC, semicolin requested changes
I just noticed that the unit tests are using the real FhirChartConfigurationService. We should probably be mocking that. You can add a test with mock `configService.timelineRange$` to fill the gap in  test coverage.

2023-01-19 14:23 UTC, yashpmohod commented
Working on this

2023-01-20 14:01 UTC, semicolin requested changes

2023-01-20 14:01 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.spec.ts
> +  it('should subscribe timelineRange when the component initializes and set minDate and maxDate', async () => {
actually, if you apply my suggested changes below, you don't need either

2023-01-23 07:11 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.spec.ts
> +  it('should subscribe timelineRange when the component initializes and set minDate and maxDate', async () => {
Okay, I will apply your suggested chnages.

2023-01-23 07:12 UTC, yashpmohod commented on projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.spec.ts
> +    })
Okay I will change test case as per your suggestion.

2023-01-23 14:33 UTC, semicolin approved these changes

2023-01-23 15:38 UTC, merged