Rt 631 use fixed layer order
elimuinformatics/charts-on-fhir pull request #90
Opened 2023-02-03 13:12 UTC by amolht

## Overview
Added fixed layer order
Order support for both medication and conservation layers  

## How it was tested
Tested on local by running cardiovascular health app on local. 

## Checklist

- [x] The title contains a short meaningful summary
- [x] I have added a link to this PR in the Jira issue
- [x] I have described how this was tested
- [x] I have included screen shots for changes that affect the user interface
- [ ] I have updated unit tests
- [x] I have run unit tests locally
- [ ] I have updated documentation (including README)

2023-02-03 13:13 UTC, amolht commented
![Screenshot from 2023-02-03 18-41-46](https://user-images.githubusercontent.com/57406228/216612051-d767b33c-d2d2-4d71-8bcc-2e6dec4b4df4.png)

2023-02-03 15:07 UTC, semicolin requested changes
I don't think we need to support pre-selecting a specific list of layers. We can just auto-select all or none.

2023-02-03 15:07 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
> +    ))
1. Why does this need to duplicate the code from the select method? can it just call the method instead?
2. If you are not using the return value of `map`, use `forEach` or a `for...of` loop instead.

2023-02-03 15:07 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
>        },
So the layers will not show up until all data has finished loading?

2023-02-03 15:36 UTC, semicolin commented
> I don't think we need to support pre-selecting a specific list of layers. We can just auto-select all or none.

Sorry, I forgot that the list is also defining the layer order. Can we try using `layer.scale.weight` to define the order?

2023-02-06 13:33 UTC, amolht commented
> > I don't think we need to support pre-selecting a specific list of layers. We can just auto-select all or none.
> 
> Sorry, I forgot that the list is also defining the layer order. Can we try using `layer.scale.weight` to define the order?

2023-02-06 13:35 UTC, amolht commented
@semicolin, I have tried with `layer.scale.weight` but it only orders chat layers not selected layers and statistic cards.

2023-02-07 17:33 UTC, semicolin requested changes
Please simplify the API. The type for the `layerOrder` parameter is confusing and I don't understand why the client code needs all those rxjs operators just to implement a sort callback. Take a look at other APIs that use a sort callback to get ideas (e.g. Array.sort or _.sortBy).

2023-02-07 17:33 UTC, semicolin commented on projects/cardiovascular-health/src/app/app.component.ts
> +      toArray(),
`toArray` waits until the observable competes before emitting anything. I don't think that's what we want here

2023-02-07 17:33 UTC, semicolin commented on projects/cardiovascular-health/src/app/app.component.ts
> +      mergeAll()
Why are you using `mergeAll` here? Is this really a higher-order observable? It doesn't look like it based on the declared types in DataLayerManager.

2023-02-07 17:33 UTC, semicolin commented on projects/cardiovascular-health/src/app/app.component.ts
> +  orderLayers(layer: any) {
Please declare the parameter type. Type-checking is very helpful for code like this.

2023-02-08 17:31 UTC, semicolin requested changes

2023-02-15 14:03 UTC, semicolin requested changes

2023-02-15 14:03 UTC, semicolin commented on projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
> +    return Object.keys(this.state.layers).reduce((nextState, id) => this.selectLayer(nextState, id), state);
this should be using layers from the state parameter, not the instance property
```suggestion
    return Object.keys(state.layers).reduce((nextState, id) => this.selectLayer(nextState, id), state);
```

2023-02-15 14:18 UTC, semicolin commented
We should add unit tests for sort and selectAll

2023-02-16 16:55 UTC, semicolin approved these changes

2023-02-17 07:17 UTC, yashpmohod approved these changes

2023-02-20 06:13 UTC, merged